import { useEffect, useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import { ArrowUpRight, ChevronDown, ChevronRight, GitBranch, Radio, Search } from 'lucide-react';
import { allRecords } from '../lib/api';
import type { RecordData } from '../lib/types';
import { EmptyState, ErrorMessage, Loading, PageHeading } from '../components/Shared';

export default function Hierarchy() {
  const [records, setRecords] = useState<RecordData[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState<unknown>(null); const [search, setSearch] = useState('');
  useEffect(() => { let active = true; allRecords<RecordData>('devices/').then(result => { if (active) setRecords(result); }).catch(e => { if (active) setError(e); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, []);
  const children = useMemo(() => { const map = new Map<number, RecordData[]>(); for (const row of records) if (row.parent) { const parent = Number(row.parent); map.set(parent, [...(map.get(parent) || []), row]); } return map; }, [records]);
  const visible = useMemo(() => { if (!search.trim()) return null; const ids = new Set<number>(); const byId = new Map(records.map(row => [row.id, row])); for (const row of records) if (`${row.name} ${row.code}`.toLowerCase().includes(search.trim().toLowerCase())) { let node: RecordData | undefined = row; const seen = new Set<number>(); while (node && !seen.has(node.id)) { seen.add(node.id); ids.add(node.id); node = byId.get(Number(node.parent)); } } return ids; }, [records, search]);
  const roots = records.filter(row => !row.parent || !records.some(parent => parent.id === Number(row.parent)));
  return <><PageHeading eyebrow="DEVICE RELATIONSHIPS" title="Equipment hierarchy" description="Follow the connections from stations and gateways down to individual sensors." actions={<Link className="button button-secondary" to="/devices">Manage devices <ArrowUpRight size={16}/></Link>}/><ErrorMessage error={error}/><section className="panel"><div className="table-toolbar"><div className="search-box"><Search size={17}/><input aria-label="Search hierarchy" placeholder="Find a device…" value={search} onChange={e => setSearch(e.target.value)}/></div><span className="muted">{records.length} devices · {roots.length} roots</span></div>{loading ? <Loading/> : records.length && (!visible || visible.size) ? <div className="device-tree" role="tree" aria-label="Device hierarchy">{roots.filter(row => !visible || visible.has(row.id)).map(row => <TreeNode key={row.id} row={row} childrenMap={children} visible={visible} depth={0}/>)}</div> : <EmptyState icon={<GitBranch size={28}/>} title={search ? 'No matching devices' : 'Every network starts with a device'}>{search ? 'Try a device name or code.' : 'Create devices and select a parent device to build your hierarchy.'}</EmptyState>}</section></>;
}
function TreeNode({ row, childrenMap, visible, depth }: { row: RecordData; childrenMap: Map<number, RecordData[]>; visible: Set<number> | null; depth: number }) {
  const [open, setOpen] = useState(true); const items = (childrenMap.get(row.id) || []).filter(child => !visible || visible.has(child.id));
  useEffect(() => { if (visible) setOpen(true); }, [visible]);
  return <div role="treeitem" aria-expanded={items.length ? open : undefined} className="tree-node"><div className="tree-row">{items.length ? <button className="icon-button" onClick={() => setOpen(!open)} aria-label={`${open ? 'Collapse' : 'Expand'} ${row.name}`}>{open ? <ChevronDown size={17}/> : <ChevronRight size={17}/>}</button> : <span className="tree-spacer"/>}<span className="record-glyph"><Radio size={18}/></span><Link to={`/devices?record=${row.id}`}><strong>{String(row.name)}</strong><small>{String(row.code)}</small></Link>{items.length > 0 && <span className="badge">{items.length} connected</span>}<Link className="icon-button" aria-label={`View ${row.name}`} to={`/devices?record=${row.id}`}><ArrowUpRight size={16}/></Link></div>{open && items.length > 0 && <div className="tree-children" role="group">{items.map(child => <TreeNode key={child.id} row={child} childrenMap={childrenMap} visible={visible} depth={depth + 1}/>)}</div>}</div>;
}
