import { demoMode } from '../lib/demo';
import { useState } from 'react';
import { Link, useSearchParams } from 'react-router-dom';
import { ArrowRight, Check, CheckCircle2, Download, FileSpreadsheet, ShieldCheck, Upload } from 'lucide-react';
import { api, ApiError } from '../lib/api';
import { ErrorMessage, PageHeading, useNotice } from '../components/Shared';

interface ImportResult { valid: boolean; total_rows: number; errors: { sheet: string; row: number; field: string; message: string }[]; preview: Record<string, unknown>[] }
export default function ImportPage() {
  const [params] = useSearchParams(); const notice = useNotice();
  const initialEntity = params.get('entity');
  const [entity, setEntity] = useState(initialEntity && ['devices', 'assets', 'measurements'].includes(initialEntity) ? initialEntity : 'devices');
  const [file, setFile] = useState<File | null>(null); const [result, setResult] = useState<ImportResult | null>(null);
  const [error, setError] = useState<unknown>(null); const [busy, setBusy] = useState(''); const [imported, setImported] = useState<number | null>(null);
  async function upload(action: 'validate' | 'commit') {
    if (!file) return; setBusy(action); setError(null);
    const body = new FormData(); body.append('entity', entity); body.append('file', file);
    try {
      if (action === 'validate') setResult(await api<ImportResult>('imports/validate/', { method: 'POST', body }));
      else { const response = await api<{ imported: number }>('imports/commit/', { method: 'POST', body }); setImported(response.imported); notice(`${response.imported} ${entity} imported successfully.`); }
    } catch (e) {
      if (e instanceof ApiError && e.details && typeof e.details === 'object' && 'errors' in e.details) {
        const details = e.details as ImportResult; setResult({ valid: false, total_rows: details.total_rows || 0, errors: details.errors || [], preview: details.preview || [] });
        setError(action === 'commit' ? new Error('The import was rolled back. Resolve the errors below and upload the corrected file.') : null);
      } else setError(e);
    } finally { setBusy(''); }
  }
  function reset() { setFile(null); setResult(null); setImported(null); setError(null); }
  return <><PageHeading eyebrow="BULK DATA TOOLS" title="Bring your records together." description="Import a spreadsheet, check every row, and add your metadata with confidence."/><div className="import-layout"><section className="panel import-main"><div className="import-steps">{['Choose a file', 'Review & validate', 'Import records'].map((label, i) => <div className={(imported !== null ? 2 : result ? 1 : 0) >= i ? 'active' : ''} key={label}><span>{(imported !== null ? 3 : result?.valid ? 1 : 0) > i ? <Check size={15}/> : i + 1}</span>{label}</div>)}</div><div className="import-content">{demoMode && <div className="demo-banner"><strong>Import preview only</strong><span>Template downloads and spreadsheet processing need the backend. Explore the layout here, or add sample records from the registry pages.</span></div>}<ErrorMessage error={error}/>{imported !== null ? <div className="import-success"><CheckCircle2 size={49}/><h2>Your records are in.</h2><p>{imported} {entity} were imported successfully. All records belong to your department.</p><div className="button-row"><button className="button button-secondary" onClick={reset}>Import another file</button><Link className="button" to={`/${entity}`}>View {entity}<ArrowRight size={16}/></Link></div></div> : <>
      <div className="form-field"><label htmlFor="import-entity">What are you importing?</label><select id="import-entity" value={entity} disabled={demoMode || !!busy} onChange={e => { setEntity(e.target.value); reset(); }}><option value="devices">Devices</option><option value="assets">Assets</option><option value="measurements">Measurements</option></select></div>
      <div className="template-banner"><FileSpreadsheet size={24}/><div><strong>Start with the right structure</strong><span>Use our {entity} template to match the expected columns.</span></div>{demoMode ? <button className="button button-secondary" disabled><Download size={15}/>Template</button> : <a className="button button-secondary" href={`/api/v1/imports/template/?entity=${entity}`} download><Download size={15}/>Template</a>}</div>
      <label className={`upload-zone ${file ? 'has-file' : ''}`}><input type="file" accept=".xlsx,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" disabled={demoMode || !!busy} onChange={e => { setFile(e.target.files?.[0] || null); setResult(null); setError(null); }}/><span className="upload-icon">{file ? <FileSpreadsheet size={28}/> : <Upload size={28}/>}</span><strong>{file ? file.name : 'Choose your spreadsheet'}</strong><span>{file ? `${(file.size / 1024).toFixed(1)} KB · Click to choose another file` : 'Click to browse · Excel .xlsx files'}</span></label>
      <div className="button-row"><button className="button" disabled={demoMode || !file || !!busy} onClick={() => upload('validate')}>{busy === 'validate' ? 'Checking rows…' : 'Validate spreadsheet'}<ArrowRight size={16}/></button></div>
      {result && <section className="validation-results"><div className={`validation-heading ${result.valid ? 'valid' : 'invalid'}`}><ShieldCheck size={22}/><div><h3>{result.valid ? `${result.total_rows} rows ready to import` : `${result.errors.length} issues to resolve`}</h3><p>{result.valid ? 'All rows passed validation. No records have been saved yet.' : 'Correct the affected rows and upload the file again. No records were saved.'}</p></div></div>{result.errors.length > 0 && <div className="table-scroll"><table className="data-table"><thead><tr><th>Sheet</th><th>Row</th><th>Field</th><th>Issue</th></tr></thead><tbody>{result.errors.map((item, i) => <tr key={i}><td>{item.sheet || '—'}</td><td>{item.row || '—'}</td><td>{item.field}</td><td>{item.message}</td></tr>)}</tbody></table></div>}{result.preview.length > 0 && <><h4>Preview <span className="muted">· First {result.preview.length} rows</span></h4><div className="table-scroll"><table className="data-table"><thead><tr>{Object.keys(result.preview[0]).map(key => <th key={key}>{key.replaceAll('_', ' ')}</th>)}</tr></thead><tbody>{result.preview.map((row, i) => <tr key={i}>{Object.keys(result.preview[0]).map(key => <td key={key}>{typeof row[key] === 'object' && row[key] !== null ? JSON.stringify(row[key]) : String(row[key] ?? '—')}</td>)}</tr>)}</tbody></table></div></>}{result.valid && <div className="import-commit"><p>The file is checked again when you import. If any row fails, the entire import is rolled back.</p><button className="button" disabled={demoMode || !!busy} onClick={() => upload('commit')}><Upload size={16}/>{busy === 'commit' ? 'Importing…' : `Import ${result.total_rows} records`}</button></div>}</section>}
    </>}</div></section><aside className="import-guide"><div className="eyebrow">BEFORE YOU IMPORT</div><h2>A little preparation.<br/>A smoother import.</h2><ol><li><strong>Prepare your catalogs</strong><p>Create the types and units your records reference.</p></li><li><strong>Add your data sources</strong><p>Source codes must already exist in your department.</p></li><li><strong>Import assets and devices</strong><p>Parent devices can appear anywhere in the same device file or already exist in your department.</p></li><li><strong>Import measurements last</strong><p>Reference existing device and asset codes to connect your records.</p></li></ol><div className="info-note"><ShieldCheck size={19}/><p>Imports create new records. Duplicate codes are rejected and existing data is never silently overwritten.</p></div></aside></div></>;
}
