import { demoMode } from '../lib/demo';
import { useEffect, useState } from 'react';
import type { FormEvent } from 'react';
import { Check, Copy, ExternalLink, KeyRound, Plus, ShieldCheck, Trash2 } from 'lucide-react';
import { allRecords, mutate } from '../lib/api';
import { dateLabel, EmptyState, ErrorMessage, Loading, Modal, PageHeading, useNotice } from '../components/Shared';

interface Key { id: number; name: string; prefix: string; created_at: string; revoked_at: string | null; key?: string }
export default function KeysPage() {
  const [keys, setKeys] = useState<Key[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState<unknown>(null);
  const [refresh, setRefresh] = useState(0); const [mode, setMode] = useState<'create' | 'revoke' | 'reveal' | null>(null);
  const [selected, setSelected] = useState<Key | null>(null); const [name, setName] = useState(''); const [busy, setBusy] = useState(false); const [actionError, setActionError] = useState<unknown>(null); const [copied, setCopied] = useState(false); const notice = useNotice();
  useEffect(() => { let active = true; setLoading(true); setError(null); allRecords<Key>('api-keys/').then(result => { if (active) setKeys(result); }).catch(e => { if (active) setError(e); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, [refresh]);
  function close() { if (!busy) { setMode(null); setSelected(null); setActionError(null); setName(''); setCopied(false); } }
  async function create(event: FormEvent) { event.preventDefault(); setBusy(true); setActionError(null); try { const key = await mutate<Key>('api-keys/', 'POST', { name: name.trim() }); setSelected(key); setMode('reveal'); setRefresh(v => v + 1); } catch (e) { setActionError(e); } finally { setBusy(false); } }
  async function revoke() { if (!selected) return; setBusy(true); setActionError(null); try { await mutate(`api-keys/${selected.id}/revoke/`, 'POST'); setMode(null); setSelected(null); setRefresh(v => v + 1); notice('API key revoked.'); } catch (e) { setActionError(e); } finally { setBusy(false); } }
  async function copy() { try { await navigator.clipboard.writeText(selected?.key || ''); setCopied(true); } catch { setActionError(new Error('Your browser could not copy automatically. Select and copy the key below.')); } }
  return <><PageHeading eyebrow="WORKSPACE SETTINGS" title="API access" description="Give external applications read-only access to your department’s metadata." actions={<button className="button" onClick={() => setMode('create')}><Plus size={17}/>Create API key</button>}/>{demoMode && <div className="demo-banner">Sample keys are placeholders and cannot authenticate to any service.</div>}<div className="access-banner"><ShieldCheck size={25}/><div><strong>Scoped to your department. Read-only by design.</strong><p>API keys can retrieve metadata. They cannot change records, manage users, or import files.</p></div>{!demoMode && <a className="text-button" href="/api/docs/" target="_blank" rel="noreferrer">API reference<ExternalLink size={15}/></a>}</div><ErrorMessage error={error}/><section className="panel">{loading ? <Loading/> : keys.length ? <div className="table-scroll"><table className="data-table"><thead><tr><th>Name</th><th>Key prefix</th><th>Created</th><th>Status</th><th><span className="sr-only">Actions</span></th></tr></thead><tbody>{keys.map(key => <tr key={key.id}><td><div className="record-link"><span className="record-glyph"><KeyRound size={18}/></span><strong>{key.name}</strong></div></td><td><code>{key.prefix}…</code></td><td>{dateLabel(key.created_at)}</td><td><span className={`badge ${key.revoked_at ? '' : 'badge-green'}`}>{key.revoked_at ? 'Revoked' : 'Active'}</span></td><td>{!key.revoked_at && <button className="text-button danger-text" onClick={() => { setSelected(key); setMode('revoke'); }}>Revoke</button>}</td></tr>)}</tbody></table></div> : <EmptyState icon={<KeyRound size={29}/>} title="Connect your external systems">Create a key to let a trusted application read your department’s metadata.</EmptyState>}</section>
    {mode && <Modal title={mode === 'create' ? 'Create API key' : mode === 'revoke' ? 'Revoke API key?' : 'Save your new API key'} onClose={close}>{mode === 'create' ? <form onSubmit={create}><div className="modal-body"><ErrorMessage error={actionError}/><div className="form-field"><label htmlFor="key-name">Key name <span className="required">*</span></label><input id="key-name" value={name} onChange={e => setName(e.target.value)} required placeholder="e.g. Production collector" maxLength={120}/><p className="field-hint">Use a name that identifies the application using this key.</p></div></div><footer className="modal-footer"><button type="button" className="button button-secondary" onClick={close} disabled={busy}>Cancel</button><button className="button" disabled={busy || !name.trim()}>{busy ? 'Creating…' : 'Create key'}</button></footer></form> : mode === 'reveal' ? <><div className="modal-body"><ErrorMessage error={actionError}/><p className="key-warning">This key is shown only once. Copy it now and store it securely before closing this dialog.</p><div className="key-reveal"><code>{selected?.key}</code><button className="icon-button" aria-label="Copy API key" onClick={copy}>{copied ? <Check size={19}/> : <Copy size={19}/>}</button></div><p className="field-hint">Send it as the <code>X-API-Key</code> request header.</p></div><footer className="modal-footer"><button className="button" onClick={close}>I have saved the key</button></footer></> : <><div className="modal-body"><ErrorMessage error={actionError}/><p>External applications using <strong>{selected?.name}</strong> will lose access immediately. This cannot be undone; you can create a new key if needed.</p></div><footer className="modal-footer"><button className="button button-secondary" onClick={close} disabled={busy}>Cancel</button><button className="button button-danger" onClick={revoke} disabled={busy}><Trash2 size={16}/>{busy ? 'Revoking…' : 'Revoke key'}</button></footer></>}</Modal>}
  </>;
}
